# 服务器相关配置
server:
  # 服务器监听的IP地址
  ip: 127.0.0.1
  # 监听的端口号
  port: 8089
# 数据库相关配置
database:
  # MySQL
  mysql:
    # MySQL 主机地址
    host: 127.0.0.1
    # MySQL 端口(默认3306)
    port: 3306
    # 数据库名称
    db: cloud_lock
    # 用户
    user: root
    # 密码
    password: mL&VFW3US
  # Redis
  redis:
    # Redis 主机地址
    host: 127.0.0.1
    # Redis 端口号(默认6379)
    port: 6379
    # 数据库序号(默认0)
    db: 0
    # Redis 密码(默认为空)
    password: ''
  influxdb:
    enable: true
    host: 10.4.61.203
    port: 8086
    token: 'JMlafqZKc9URI0AAVr7J7i0QEGTuOX1_5qN_kmCEOf01-PypsbvowMWmHIau2EgWMs1Ak3-8kQGQZQP7nZY14w=='
    org: shawngao
    bucket: request_log
# 安全相关配置
security:
  # JWT
  jwt:
    # 加密 JWT 的私钥
    secret: 'h*Gq>Cu.0-G38oPti+-PkqA}s.g,69^t'
    # JWT 的过期时间(秒)
    timeout: 2592000
  # RSA
  rsa:
    # 公钥
    public: 'MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALEq7Tr9cumEWevYdcaEC0ZeYzxtXn5nW/8jxLYVqhu6S+jCQwovWJqi++tMUcxIDH6rZF/RSlLp6PqMNKIdI1kCAwEAAQ=='
    # 私钥
    private: 'MIIBUgIBADANBgkqhkiG9w0BAQEFAASCATwwggE4AgEAAkEAsSrtOv1y6YRZ69h1xoQLRl5jPG1efmdb/yPEthWqG7pL6MJDCi9YmqL760xRzEgMfqtkX9FKUuno+ow0oh0jWQIDAQABAj8GKMSwLrkcy5a7HEtiTptI8Ji1zeRhgJzLwfKUyF87MRZndgV9EGdmBAkUaNl8TWPOJ/GDnMuq862DCBEaw7sCIQDkLxeN75pBYF0UYGYFFXD4zHkTOvG6IwlVE0k6U/P14wIhAMbDxrxOxjURcBLRg6jmP1WifpQpBK2EzgJAKbQ7/+aTAiBW3AI4WlO6vSbRYdyT5NSLMLKJ+m8XrsyXoO7IEDsWhwIgTO59v2jmAqhLLp11TixAG08XmxT9QIQEkI5xFdebRo0CIGiC+z1wW5OShQsOIOrFsuq3NfS9kJshYzHUGzrZIVOY'
# NacOS 统一配置中心
nacos:
  # 是否启用统一配置
  enable: true
  # NacOS 主机地址
  ip: 10.4.61.203
  # NacOS 端口号(默认8848)
  port: 8848
  # 用户名
  username: nacos
  # 密码
  password: Ahhhjtll1125
  # 命名空间
  namespace: 0ead3860-538a-4029-8246-7b95f20ff526
  # 配置文件所属组
  group: dev
  # 配置文件的数据编号
  dataId: gin-config.yaml
  # 超时时长
  timeout: 5000
  # 日志级别
  loglevel: debug
# 开发者模式(开发者模式会绕过所有的权限认证)
develop: false
